# Generated by Django 6.1 on 2026-08-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lenskart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='user_token',
        ),
    ]
