# Generated by Django 6.1 on 2026-08-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lenskart', '0002_remove_login_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
