# Generated by Django 6.1 on 2026-08-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lenskart', '0004_address_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_ID',
            new_name='order',
        ),
    ]
