# Generated by Django 6.1 on 2026-08-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lenskart', '0005_rename_order_id_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
