# Generated by Django 6.1 on 2026-08-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lenskart', '0006_register_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='frame_color',
            field=models.CharField(max_length=100),
        ),
    ]
