# Generated by Django 6.1 on 2026-08-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lenskart', '0007_remove_orderitem_address_remove_orderitem_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jayakumar', max_length=100)),
                ('phone', models.CharField(default='7358906752', max_length=15, unique=True)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('user_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
