# Generated by Django 6.1 on 2026-08-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lenskart', '0008_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
