# Generated by Django 6.1 on 2026-08-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lenskart', '0009_admin_otp_created_at_register_otp_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
