# Generated by Django 6.1 on 2026-08-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lenskart', '0010_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='glass_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('category_type', models.CharField(choices=[('eyeglasses', 'Eyeglasses'), ('sunglasses', 'Sunglasses'), ('power_glass', 'Power Glass'), ('contact_lenses', 'Contact Lenses'), ('computer_bluelight', 'Computer & Blue Light')], max_length=50)),
                ('frame_size', models.CharField(choices=[('S', 'Small (S)'), ('M', 'Medium (M)'), ('L', 'Large (L)'), ('XL', 'Extra Large (XL)')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('structure_style', models.CharField(choices=[('oval', 'Oval'), ('square', 'Square'), ('rectangle', 'Rectangle'), ('round', 'Round'), ('cat_eye', 'Cat Eye'), ('aviator', 'Aviator'), ('wayfarer', 'Wayfarer'), ('geometric', 'Geometric'), ('browline', 'Browline'), ('clubmaster', 'Clubmaster'), ('rimless', 'Rimless'), ('semi_rimless', 'Semi Rimless'), ('full_rim', 'Full Rim')], max_length=50)),
                ('target_audience', models.CharField(choices=[('unisex', 'Unisex'), ('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=20)),
                ('collection_tier', models.CharField(choices=[('classic', 'Classic'), ('executive', 'Executive'), ('junior', 'Junior'), ('essential', 'Essential'), ('premium', 'Premium')], max_length=20)),
                ('includes_adjustable_nose_pad', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_year', models.PositiveIntegerField()),
                ('right_sph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('right_cyl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_axis', models.IntegerField(blank=True, null=True)),
                ('left_sph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('left_cyl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_axis', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
