# Generated by Django 6.1 on 2026-09-01 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lenskart', '0013_glass_product_color_glass_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectLens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_type', models.CharField(choices=[('single_vision', 'Single Vision'), ('zero_power', 'Zero Power'), ('bifocal_progressive', 'Bifocal / Progressive')], max_length=50)),
                ('lens_package', models.CharField(choices=[('basic_anti_glare', 'Basic Anti-Glare'), ('blu_tech', 'BLU Tech'), ('premium_hydrophobic', 'Premium Hydrophobic')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_lens', to='app_lenskart.prescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_lenses', to='app_lenskart.glass_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_lenses', to='app_lenskart.register')),
            ],
        ),
    ]
