# Generated by Django 6.1 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lenskart', '0014_selectlens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glass_product',
            name='category_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='glass_product',
            name='collection_tier',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='glass_product',
            name='frame_size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='glass_product',
            name='rating',
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                max_digits=2
            ),
        ),
        migrations.AlterField(
            model_name='glass_product',
            name='structure_style',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='glass_product',
            name='target_audience',
            field=models.CharField(max_length=20),
        ),
    ]
