# Generated by Django 6.1 on 2026-09-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lenskart', '0015_rename_model_name_glass_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glass_product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
